import type { EffectSpec } from "@shared/types";

export const DEBUFF_REGISTRY: Record<string, EffectSpec> = {
  magic_vulnerability: {
    name: "Magic Vulnerability",
    kind: "debuff",
    duration: 8,
    behavior: { kind: "vuln", damageType: "magical", multiplier: 1.5 },
  },
  magic_vulnerability_up: {
    name: "Magic Vulnerability Up",
    kind: "debuff",
    duration: 10,
    behavior: { kind: "vuln", damageType: "magical", multiplier: 2 },
  },
  physical_vulnerability: {
    name: "Physical Vulnerability",
    kind: "debuff",
    duration: 8,
    behavior: { kind: "vuln", damageType: "physical", multiplier: 1.5 },
  },
  pyretic: {
    name: "Pyretic",
    kind: "debuff",
    duration: 8,
    behavior: { kind: "dot", dps: 8, condition: "moving" },
  },
  freeze: {
    name: "Freeze",
    kind: "debuff",
    duration: 8,
    behavior: { kind: "dot", dps: 8, condition: "idle" },
  },
  sleep: {
    name: "Sleep",
    kind: "debuff",
    duration: 6,
    behavior: { kind: "sleep" },
  },
  confusion: {
    name: "Confusion",
    kind: "debuff",
    duration: 6,
    behavior: { kind: "confusion", damage: 50, damageType: "true", radius: 1.5 },
  },
  unbecoming: {
    name: "Unbecoming",
    kind: "debuff",
    duration: 999,
    icon: "unbecoming.png",
    showTimer: false,
    behavior: { kind: "escalating", escalationKey: "unbecoming", escalateTo: "mean" },
  },
  mean: {
    name: "Mean",
    kind: "debuff",
    duration: 999,
    showTimer: false,
    icon: "meanest_existence.png",
    behavior: { kind: "escalating", escalationKey: "unbecoming", escalateDamage: 999999, escalateDamageType: "true" },
  },
  damage_down: {
    name: "Damage Down",
    kind: "debuff",
    duration: 999,
    showTimer: false,
    icon: "dmg_down.png",
    behavior: { kind: "none" },
  },
  primordial_crust: {
    name: "Primordial Crust",
    kind: "debuff",
    duration: 200,
    showTimer: false,
    icon: "primoridial_crust.png",
    behavior: { kind: "primordialCrust", expiryDamage: 999999, expiryDamageType: "true" },
  },
  accretion: {
    name: "Accretion",
    kind: "debuff",
    duration: 11,
    behavior: { kind: "accretion", expiryDamage: 999999, expiryDamageType: "true" },
  },
  first_in_line: {
    name: "First in Line",
    kind: "debuff",
    duration: 200,
    showTimer: false,
    icon: "first_in_line.png",
    behavior: { kind: "assignment", expiryDamage: 20, expiryDamageType: "true" },
  },
  second_in_line: {
    name: "Second in Line",
    kind: "debuff",
    duration: 200,
    showTimer: false,
    icon: "second_in_line.png",
    behavior: { kind: "assignment", expiryDamage: 20, expiryDamageType: "true" },
  },
  third_in_line: {
    name: "Third in Line",
    kind: "debuff",
    duration: 200,
    showTimer: false,
    icon: "third_in_line.png",
    behavior: { kind: "assignment", expiryDamage: 20, expiryDamageType: "true" },
  },
  accretion_duty: {
    name: "Accretion Duty",
    kind: "debuff",
    duration: 200,
    showTimer: false,
    visibility: "invisible",
    behavior: { kind: "none" },
  },
  non_accretion_duty: {
    name: "NonAccretion Duty",
    kind: "debuff",
    duration: 200,
    showTimer: false,
    visibility: "invisible",
    behavior: { kind: "none" },
  },
  alpha: {
    name: "Alpha",
    kind: "debuff",
    duration: 20,
    icon: "alpha.png",
    behavior: { kind: "assignment", expiryDamage: 20, expiryDamageType: "true" },
  },
  beta: {
    name: "Beta",
    kind: "debuff",
    duration: 20,
    icon: "beta.png",
    behavior: { kind: "assignment", expiryDamage: 20, expiryDamageType: "true" },
  },
  dash_target: {
    name: "Dash Target",
    kind: "debuff",
    duration: 8,
    marker: "DASH",
    behavior: { kind: "none" },
  },
  spread_charge: {
    name: "Spread Charge",
    kind: "debuff",
    duration: 12,
    visibility: "invisible",
    markerIcon: "defam_processed.png",
    behavior: { kind: "none" },
  },
  stack_charge: {
    name: "Stack Charge",
    kind: "debuff",
    duration: 120,
    visibility: "invisible",
    behavior: { kind: "none" },
  },
  stack_charge_marker: {
    name: "Stack Charge Marker",
    kind: "debuff",
    duration: 5,
    visibility: "invisible",
    markerIcon: "stack_processed.png",
    behavior: { kind: "none" },
  },
  cone_charge: {
    name: "Cone Charge",
    kind: "debuff",
    duration: 120,
    visibility: "invisible",
    behavior: { kind: "none" },
  },
  cone_charge_marker: {
    name: "Cone Charge Marker",
    kind: "debuff",
    duration: 5,
    visibility: "invisible",
    markerIcon: "cone_processed.png",
    behavior: { kind: "none" },
  },
  defamation_charge: {
    name: "Defamation Charge",
    kind: "debuff",
    duration: 120,
    visibility: "invisible",
    behavior: { kind: "none" },
  },
  defamation_charge_marker: {
    name: "Defamation Charge Marker",
    kind: "debuff",
    duration: 5,
    visibility: "invisible",
    markerIcon: "defam_processed.png",
    behavior: { kind: "none" },
  },
  double_trouble: {
    name: "Double Trouble",
    kind: "debuff",
    duration: 24,
    icon: "double-trouble.png",
    behavior: { kind: "burstSpread", radius: 5, damage: 10, damageType: "magical", knockbackDistance: 14 },
  },
  plant_short: {
    name: "Plant (short)",
    kind: "debuff",
    duration: 7,
    behavior: { kind: "plant", direction: [0, 1], distance: 6.5, radius: 1.7, armDelay: 3, duration: 20, tpDelay: 1.25 },
  },
  plant_long: {
    name: "Plant (long)",
    kind: "debuff",
    duration: 10,
    behavior: { kind: "plant", direction: [0, 1], distance: 6.5, radius: 1.7, armDelay: 3, duration: 20, tpDelay: 1.25 },
  },
  headwind: {
    name: "Headwind",
    kind: "debuff",
    duration: 9,
    behavior: { kind: "directionalKnockback", requiredFacing: "toward", distance: 10, doubledDistance: 22 },
  },
  tailwind: {
    name: "Tailwind",
    kind: "debuff",
    duration: 9,
    behavior: { kind: "directionalKnockback", requiredFacing: "away", distance: 10, doubledDistance: 22 },
  },
  epic_hero: {
    name: "Epic Hero",
    kind: "debuff",
    duration: 200,
    showTimer: false,
    icon: "alpha.png",
    behavior: { kind: "assignment", expiryDamage: 0, expiryDamageType: "true" },
  },
  fated_hero: {
    name: "Fated Hero",
    kind: "debuff",
    duration: 200,
    showTimer: false,
    icon: "beta.png",
    behavior: { kind: "assignment", expiryDamage: 0, expiryDamageType: "true" },
  },
  bowels_headwind: {
    name: "Headwind",
    kind: "debuff",
    duration: 70,
    icon: "headwind.png",
    behavior: { kind: "directionalKnockback", requiredFacing: "away", distance: 8, doubledDistance: 18 },
  },
  bowels_tailwind: {
    name: "Tailwind",
    kind: "debuff",
    duration: 70,
    icon: "tailwind.png",
    behavior: { kind: "directionalKnockback", requiredFacing: "toward", distance: 8, doubledDistance: 18 },
  },
  entropy_short: {
    name: "Entropy Short",
    kind: "debuff",
    duration: 18,
    icon: "entropy.png",
    behavior: {
      kind: "burstSpread",
      selfShape: "circle",
      radius: 5,
      damage: 8,
      damageType: "magical",
      knockbackDistance: 0,
      followUp: { mode: "closest", count: 2, originCrystal: "fire", shape: "donut", radius: 8, inner: 3, damage: 12, damageType: "magical" },
    },
  },
  entropy_long: {
    name: "Entropy Long",
    kind: "debuff",
    duration: 45,
    icon: "entropy.png",
    behavior: {
      kind: "burstSpread",
      selfShape: "circle",
      radius: 5,
      damage: 8,
      damageType: "magical",
      knockbackDistance: 0,
      followUp: { mode: "closest", count: 2, originCrystal: "fire", shape: "donut", radius: 8, inner: 3, damage: 12, damageType: "magical" },
    },
  },
  dynamic_fluid_short: {
    name: "Dynamic Fluid Short",
    kind: "debuff",
    duration: 18,
    icon: "dynamic_fluid.png",
    behavior: {
      kind: "burstSpread",
      selfShape: "donut",
      selfInner: 3,
      radius: 8,
      damage: 12,
      damageType: "magical",
      knockbackDistance: 0,
      followUp: { mode: "closest", count: 2, originCrystal: "water", shape: "circle", radius: 5, damage: 8, damageType: "magical" },
    },
  },
  dynamic_fluid_long: {
    name: "Dynamic Fluid Long",
    kind: "debuff",
    duration: 45,
    icon: "dynamic_fluid.png",
    behavior: {
      kind: "burstSpread",
      selfShape: "donut",
      selfInner: 3,
      radius: 8,
      damage: 12,
      damageType: "magical",
      knockbackDistance: 0,
      followUp: { mode: "closest", count: 2, originCrystal: "water", shape: "circle", radius: 5, damage: 8, damageType: "magical" },
    },
  },
  debug_entropy: {
    name: "Entropy",
    kind: "debuff",
    duration: 18,
    icon: "entropy.png",
    behavior: {
      kind: "burstSpread",
      selfShape: "circle",
      radius: 6,
      damage: 80,
      damageType: "magical",
      knockbackDistance: 6,
      followUp: { mode: "closest", count: 2, shape: "donut", radius: 8, inner: 3, damage: 120, damageType: "magical" },
    },
  },
  debug_dynamic_fluid: {
    name: "Dynamic Fluid",
    kind: "debuff",
    duration: 18,
    icon: "dynamic_fluid.png",
    behavior: {
      kind: "burstSpread",
      selfShape: "donut",
      selfInner: 3,
      radius: 8,
      damage: 120,
      damageType: "magical",
      knockbackDistance: 6,
      followUp: { mode: "closest", count: 2, shape: "circle", radius: 6, damage: 80, damageType: "magical" },
    },
  },
} satisfies Record<string, EffectSpec>;
