import { join } from "path";
import {
  MAX_RAIDS,
  RAID_SEGMENT_REGEX,
  normalizeRaidName,
  type RaidCategory,
  type RaidEntry,
} from "../src/shared/protocol";

const ROOT = join(import.meta.dir, "..");
const RAIDS_DIR = join(ROOT, "raids");
const OUTPUT = join(ROOT, "src", "client", "staticRaids.generated.ts");

async function parseFile(path: string): Promise<unknown> {
  return Bun.YAML.parse(await Bun.file(path).text());
}

async function readObject(basePath: string): Promise<unknown> {
  for (const extension of [".yaml", ".yml"]) {
    const file = Bun.file(basePath + extension);
    if (await file.exists()) return parseFile(basePath + extension);
  }
  throw new Error(`No raid file found at ${basePath} (.yaml/.yml)`);
}

async function categoryFiles(categoryId: string): Promise<Map<string, string>> {
  const files = new Map<string, string>();
  for (const extension of [".yaml", ".yml"] as const) {
    for (const file of await Array.fromAsync(new Bun.Glob(`*${extension}`).scan(join(RAIDS_DIR, categoryId)))) {
      const segment = file.slice(0, -extension.length);
      if (!files.has(segment)) files.set(segment, file);
    }
  }
  return files;
}

const categoryMap = new Map<string, string>();
for (const extension of [".yaml", ".yml"] as const) {
  for (const raw of await Array.fromAsync(new Bun.Glob(`*/raid_info${extension}`).scan(RAIDS_DIR))) {
    const infoFile = raw.replaceAll("\\", "/");
    const categoryId = infoFile.slice(0, infoFile.indexOf("/"));
    if (!categoryMap.has(categoryId)) categoryMap.set(categoryId, infoFile);
  }
}

const catalog: RaidCategory[] = [];
const definitions: Record<string, { raid: unknown; bots?: unknown }> = {};
let total = 0;

for (const [categoryId, infoFile] of [...categoryMap.entries()].sort(([a], [b]) => a.localeCompare(b))) {
  if (total >= MAX_RAIDS) break;
  if (!RAID_SEGMENT_REGEX.test(categoryId)) continue;

  const info = await parseFile(join(RAIDS_DIR, infoFile)) as { name?: unknown; description?: unknown };
  const categoryName = normalizeRaidName(info.name);
  if (!categoryName) continue;

  const raids: RaidEntry[] = [];
  const files = await categoryFiles(categoryId);
  for (const [segment, file] of [...files.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    if (total >= MAX_RAIDS) break;
    if (!RAID_SEGMENT_REGEX.test(segment) || segment === "raid_info" || segment.endsWith("-bots")) continue;

    const raid = await parseFile(join(RAIDS_DIR, categoryId, file)) as { name?: unknown; botPatterns?: unknown };
    const raidName = normalizeRaidName(raid.name);
    if (!raidName) continue;

    const id = `${categoryId}/${segment}`;
    const definition: { raid: unknown; bots?: unknown } = { raid };
    if (typeof raid.botPatterns === "string") {
      definition.bots = await readObject(join(RAIDS_DIR, categoryId, raid.botPatterns));
    }
    definitions[id] = definition;
    raids.push({ id, name: raidName });
    total++;
  }

  catalog.push({
    id: categoryId,
    name: categoryName,
    description: typeof info.description === "string" ? info.description : "",
    raids,
  });
}

const output = `// GENERATED by scripts/generate-static-raids.ts — do not edit.\n\n` +
  `import type { RaidCategory } from "@shared/protocol";\n\n` +
  `export const RAID_CATALOG: RaidCategory[] = ${JSON.stringify(catalog, null, 2)};\n\n` +
  `export const RAID_DEFS: Record<string, { raid: unknown; bots?: unknown }> = ${JSON.stringify(definitions, null, 2)};\n`;

await Bun.write(OUTPUT, output);
console.log(`Generated ${OUTPUT} (${total} raids)`);
